language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
script:
  - npm run bootstrap
  - npm test
  - npm run lint
  - sonar-scanner

addons:
  sonarcloud:
    organization: "dwethmar-github"
    token:
      secure: "$SONAR_TOKEN"
